### PR TITLE
Include link to CRAN in name

### PR DESCRIPTION
**Pull request by peterdesmet**
PS: I like git (cf. [contribution](https://github.com/sckott/rforcats/blob/gh-pages/Contribute.md#nogit), but I'm still working myself up to using `knitr()` :blush:

### CODE REVIEW

**Comment by sckott** [comment]
@peterdesmet  Thanks for this change! 

Seems like we should add a section `If you like git, but don't do knitr/etc.`

**Comment by sckott** [comment]
change is up http://rforcats.net/#packages

and new contribute section http://rforcats.net/Contribute/#gitlessr

**Comment by peterdesmet** [comment]
:smile: not sure the _If you like git, but aren’t that familiar with R_ option offers much benefits over the _If you don’t like git_ and is thus required. Blame GitHub: that made all of this super easy.

I would actually have only 2 options:
- **I'm the Puss in Boots of git and R** (i.e. you know your way around) 
- **I'm a git and R kitty** (i.e. you're lazy or still learning)

**Comment by sckott** [comment]
right, perhaps you're right, i'll see about making it simpler

**Pull request merged**
